//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaraphonSkills.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance
    {
        public int DistanceId { get; set; }
        public int MarathonId { get; set; }
        public int DistanceValue { get; set; }
    
        public virtual user3 user3 { get; set; }
    }
}
