//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaraphonSkills.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.RegistrationEvent = new HashSet<RegistrationEvent>();
        }
    
        public int EventId { get; set; }
        public string EventName { get; set; }
        public int EventTypeId { get; set; }
        public int MarathonId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public decimal Cost { get; set; }
        public int MaxParticipants { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual user3 user3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationEvent> RegistrationEvent { get; set; }
    }
}
