//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaraphonSkills.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public Nullable<int> VolunteerId { get; set; }
        public Nullable<int> MarathonId { get; set; }
        public int ReviewMark { get; set; }
        public string ReviewDescription { get; set; }
        public System.DateTime ReviewDateTime { get; set; }
    
        public virtual user3 user3 { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
