//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaraphonSkills.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int SponsorId { get; set; }
        public int CharityId { get; set; }
        public int RunnerId { get; set; }
        public string Name { get; set; }
        public string CardName { get; set; }
        public int CardMonth { get; set; }
        public int CardYear { get; set; }
        public int CVCCode { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Charity Charity { get; set; }
        public virtual Runner Runner { get; set; }
    }
}
